//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LogMessagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogMessagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.LogMessagesRes", typeof(LogMessagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active window not found.
        /// </summary>
        public static string ActiveWindowNotFound {
            get {
                return ResourceManager.GetString("ActiveWindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred: {0}.
        /// </summary>
        public static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing URL {0}: {1}.
        /// </summary>
        public static string ErrorProcessingURL {
            get {
                return ResourceManager.GetString("ErrorProcessingURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while closing Chrome: {0}.
        /// </summary>
        public static string ErrorWhileClosingChrome {
            get {
                return ResourceManager.GetString("ErrorWhileClosingChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get window rectangle: {0}.
        /// </summary>
        public static string FailedGetWindowRectangle {
            get {
                return ResourceManager.GetString("FailedGetWindowRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the image: {0}.
        /// </summary>
        public static string FailedToLoadImage {
            get {
                return ResourceManager.GetString("FailedToLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted phone number {0} is invalid..
        /// </summary>
        public static string FormattedPhoneIsInvalid {
            get {
                return ResourceManager.GetString("FormattedPhoneIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image file not found at path: {0}.
        /// </summary>
        public static string ImageFileNotFound {
            get {
                return ResourceManager.GetString("ImageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format: {0}, skipping....
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message already sent to Url: {0}, skipping....
        /// </summary>
        public static string MessageAlreadySent {
            get {
                return ResourceManager.GetString("MessageAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must be 10 digits long..
        /// </summary>
        public static string PhoneNumberDigitLongError {
            get {
                return ResourceManager.GetString("PhoneNumberDigitLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number not found..
        /// </summary>
        public static string PhoneNumberNotFound {
            get {
                return ResourceManager.GetString("PhoneNumberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp window not found..
        /// </summary>
        public static string WhatsappWindowNotFound {
            get {
                return ResourceManager.GetString("WhatsappWindowNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window with title &apos;{0}&apos; not found..
        /// </summary>
        public static string WindowNotFound {
            get {
                return ResourceManager.GetString("WindowNotFound", resourceCulture);
            }
        }
    }
}
