//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PopupMessagesRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PopupMessagesRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.PopupMessagesRes", typeof(PopupMessagesRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni mesaj əlavə edildi..
        /// </summary>
        public static string AddedNewMessage {
            get {
                return ResourceManager.GetString("AddedNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajları yükləmək mümkün olmadı..
        /// </summary>
        public static string CantLoadMessageTemplates {
            get {
                return ResourceManager.GetString("CantLoadMessageTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nömrələr yüklənmədi!.
        /// </summary>
        public static string CantLoadNumbers {
            get {
                return ResourceManager.GetString("CantLoadNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nömrəsi daxil edilməyib!.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj əlavə edilərkən xəta baş verdi!.
        /// </summary>
        public static string ErrorWhileAddingMessage {
            get {
                return ResourceManager.GetString("ErrorWhileAddingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nömrələri təyin edərkən xəta baş verdi: {0}.
        /// </summary>
        public static string ErrorWhileAssignNumbers {
            get {
                return ResourceManager.GetString("ErrorWhileAssignNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj silinərkən xəta baş verdi!.
        /// </summary>
        public static string ErrorWhileDeletingMessage {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj yenilənərkən xəta baş verdi!.
        /// </summary>
        public static string ErrorWhileUpdatingMessage {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nömrə statusu dəyişdirilən zaman xəta baş verdi!.
        /// </summary>
        public static string ErrorWhileUpdatingMessageStatus {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingMessageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəyişikliklər yadda saxlanıldı!.
        /// </summary>
        public static string General_ChangesSaved {
            get {
                return ResourceManager.GetString("General_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəhmət olmasa düzgün token daxil edin!.
        /// </summary>
        public static string General_PleaseEnterValidToken {
            get {
                return ResourceManager.GetString("General_PleaseEnterValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gözlənilməyən xəta baş verdi!.
        /// </summary>
        public static string General_UnexpectedErrorOccured {
            get {
                return ResourceManager.GetString("General_UnexpectedErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj boş ola bilməz..
        /// </summary>
        public static string MessageCantBeEmpty {
            get {
                return ResourceManager.GetString("MessageCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj silindi..
        /// </summary>
        public static string MessageDeleted {
            get {
                return ResourceManager.GetString("MessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj {0} simvoldan çox ola bilməz..
        /// </summary>
        public static string MessageMaxLengthExceeded {
            get {
                return ResourceManager.GetString("MessageMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj yeniləndi..
        /// </summary>
        public static string MessageUpdated {
            get {
                return ResourceManager.GetString("MessageUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nömrə siyahısı boşdur ya da mesaj göndərilməmiş nömrə yoxdur.
        /// </summary>
        public static string NoAnyAssignedNumber {
            get {
                return ResourceManager.GetString("NoAnyAssignedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj şablonları mövcud deyil!.
        /// </summary>
        public static string NoExistingMessageTemplates {
            get {
                return ResourceManager.GetString("NoExistingMessageTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni nömrələr uğurla təyin edildi..
        /// </summary>
        public static string NumbersAssigned {
            get {
                return ResourceManager.GetString("NumbersAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siz birdən çox şablon mesaj əlavə edə bilməzsiniz! Zəhmət olmasa paketinizi yüksəldin!.
        /// </summary>
        public static string PermissionDeniedForMultipleMessageTemplates {
            get {
                return ResourceManager.GetString("PermissionDeniedForMultipleMessageTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni nömrələr əldə etmək üçün gözləməlisiniz: {0}.
        /// </summary>
        public static string RemainingTimeLimitIssue {
            get {
                return ResourceManager.GetString("RemainingTimeLimitIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistik məlumatlar yüklənmədi!.
        /// </summary>
        public static string StatisticsNotLoaded {
            get {
                return ResourceManager.GetString("StatisticsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diqqət!.
        /// </summary>
        public static string Title_Attention {
            get {
                return ResourceManager.GetString("Title_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xəta baş verdi!.
        /// </summary>
        public static string Title_ErrorOccured {
            get {
                return ResourceManager.GetString("Title_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat.
        /// </summary>
        public static string Title_Info {
            get {
                return ResourceManager.GetString("Title_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səs mesajı göndəriləcək nömrə dəyişməlidir!.
        /// </summary>
        public static string VoiceMessageNumberShouldBeChanged {
            get {
                return ResourceManager.GetString("VoiceMessageNumberShouldBeChanged", resourceCulture);
            }
        }
    }
}
