//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.UIRes", typeof(UIRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokenin etibarlılıq müddəti bitib!.
        /// </summary>
        public static string API_TokenExpired {
            get {
                return ResourceManager.GetString("API_TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token yalnışdır!.
        /// </summary>
        public static string API_TokenNotFound {
            get {
                return ResourceManager.GetString("API_TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni nömrələr təyin et.
        /// </summary>
        public static string DataOperations_AssignNewNumbersBtn {
            get {
                return ResourceManager.GetString("DataOperations_AssignNewNumbersBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son yenilənmə vaxtı: {0}.
        /// </summary>
        public static string DataOperations_LastAssignTimeText {
            get {
                return ResourceManager.GetString("DataOperations_LastAssignTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hər yenilənmədə əldə olunan nömrə: {0}.
        /// </summary>
        public static string DataOperations_LimitPerRequestText {
            get {
                return ResourceManager.GetString("DataOperations_LimitPerRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni nömrələr əldə etmək üçün gözləməlisiniz: {0}.
        /// </summary>
        public static string DataOperations_RemainingTimeLimitIssue {
            get {
                return ResourceManager.GetString("DataOperations_RemainingTimeLimitIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesaj göndərilən nömrələr: {0}.
        /// </summary>
        public static string DataOperations_SentMessageNumberCountText {
            get {
                return ResourceManager.GetString("DataOperations_SentMessageNumberCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Təyin edilmiş nömrələr: {0}.
        /// </summary>
        public static string DataOperations_TotalAssignedNumbersCountText {
            get {
                return ResourceManager.GetString("DataOperations_TotalAssignedNumbersCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göndərilmək üçün gözləyən nömrələr: {0}.
        /// </summary>
        public static string DataOperations_WaitingForSendingMessageCountText {
            get {
                return ResourceManager.GetString("DataOperations_WaitingForSendingMessageCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıxış.
        /// </summary>
        public static string ExitAppBtn {
            get {
                return ResourceManager.GetString("ExitAppBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin şifrəsi yalnışdır!.
        /// </summary>
        public static string General_AdminPasswordIsWrong {
            get {
                return ResourceManager.GetString("General_AdminPasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elan yeniləndi!.
        /// </summary>
        public static string General_AdUpdated {
            get {
                return ResourceManager.GetString("General_AdUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diqqət!.
        /// </summary>
        public static string General_Attention {
            get {
                return ResourceManager.GetString("General_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dəyişikliklər yadda saxlanıldı!.
        /// </summary>
        public static string General_ChangesSaved {
            get {
                return ResourceManager.GetString("General_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopyalama.
        /// </summary>
        public static string General_Copy {
            get {
                return ResourceManager.GetString("General_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xəta baş verdi!.
        /// </summary>
        public static string General_ErrorOccured {
            get {
                return ResourceManager.GetString("General_ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu özəllik əlavə edilməyib və ya dəstəklənmir!.
        /// </summary>
        public static string General_FeatureNotImplementedOrSupported {
            get {
                return ResourceManager.GetString("General_FeatureNotImplementedOrSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id tapılmadı!.
        /// </summary>
        public static string General_IdNotFound {
            get {
                return ResourceManager.GetString("General_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat.
        /// </summary>
        public static string General_Info {
            get {
                return ResourceManager.GetString("General_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zəhmət olmasa düzgün token daxil edin!.
        /// </summary>
        public static string General_PleaseEnterValidToken {
            get {
                return ResourceManager.GetString("General_PleaseEnterValidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gözlənilməyən xəta baş verdi!.
        /// </summary>
        public static string General_UnexpectedErrorOccured {
            get {
                return ResourceManager.GetString("General_UnexpectedErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Məlumat Əməliyyatları.
        /// </summary>
        public static string MainWindow_DataOperationsTab {
            get {
                return ResourceManager.GetString("MainWindow_DataOperationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şablon Mesajlar.
        /// </summary>
        public static string MainWindow_MessageOperationsTab {
            get {
                return ResourceManager.GetString("MainWindow_MessageOperationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametrlər.
        /// </summary>
        public static string MainWindow_SettingsOperationsTab {
            get {
                return ResourceManager.GetString("MainWindow_SettingsOperationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whatsapp Əməliyyatları.
        /// </summary>
        public static string MainWindow_WhatsappOperationsTab {
            get {
                return ResourceManager.GetString("MainWindow_WhatsappOperationsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nömrəsi daxil edilməyib!.
        /// </summary>
        public static string SettingsOperations_EnterPhoneNumber {
            get {
                return ResourceManager.GetString("SettingsOperations_EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yadda saxla.
        /// </summary>
        public static string SettingsOperations_SaveBtn {
            get {
                return ResourceManager.GetString("SettingsOperations_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səs mesajı yönləndiriləcək nömrə.
        /// </summary>
        public static string SettingsOperations_VoiceMessagePhoneNumberTextBlock {
            get {
                return ResourceManager.GetString("SettingsOperations_VoiceMessagePhoneNumberTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müştərilərə mesaj göndər.
        /// </summary>
        public static string WhatsappOperations_SendMessagesBtn {
            get {
                return ResourceManager.GetString("WhatsappOperations_SendMessagesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Səs mesajı göndərilsin.
        /// </summary>
        public static string WhatsappOperations_SendVoiceMessageText {
            get {
                return ResourceManager.GetString("WhatsappOperations_SendVoiceMessageText", resourceCulture);
            }
        }
    }
}
